import Head from 'next/head';
import styled from 'styled-components';
import Navbar from '../Components/header/Navbar';
import LogInCard from '../Components/auth/LogInCard';
import { LandingPage } from 'Components/LandingPage';
import { useSession } from 'next-auth/react';
import { Session } from 'next-auth';

const Home = (props: any) => {
  const { data: session }: { data: Session | null } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LogInCard />

      <Navbar session={session} />
      <LandingPage session={session} />
    </>
  );
};

export default Home;
