import Head from 'next/head';
import { useState } from 'react';
import Navbar from '../Components/header/Navbar';
import LogInCard from '../Components/auth/LogInCard';
import { LandingPage } from 'Components/LandingPage';
import { useSession } from 'next-auth/react';
import { Session } from 'next-auth';
import { signIn, signOut } from 'next-auth/react';
const Home = (props: any) => {
  const [isOpen, setIsOpen] = useState(false);
  const { data: session }: { data: Session | null } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isOpen && <LogInCard setIsOpen={setIsOpen} />}
      <Navbar session={session} />
      <LandingPage session={session} />
      <button
        className="bg-slate-500 rounded-md"
        onClick={() => {
          setIsOpen(true);
        }}
      >
        Log in
      </button>
      <button
        className="bg-slate-500 rounded-md ml-10"
        onClick={() => {
          signOut();
        }}
      >
        Log out
      </button>
    </>
  );
};

export default Home;
